#!/bin/bash
# ----------------------
# properties_locale_diff
# ----------------------
#   compare foundation localization property files by diffing each
#   locale file against its base language file (e.g., sv_SE vs. sv)  

FILE_PREFIX="/home/pie/promethean/foundation/parent-service/src/main/resources/parent_"
FILE_SUFFIX=".properties"

file_name() {
    echo "${FILE_PREFIX}$1${FILE_SUFFIX}"
}

locales=("cs_CZ" "da_DK" "de_DE" "el_GR" "en_US" "es_es" "fi_FI" "fr_FR" "hu_HU" "it_IT" "lv_LV" "nb_NO" "nl_NL" "pl_PL" "pt_PT" "ru_RU" "sv_SE" "th_TH" "tr_TR" "vi_VN" "zh_CN")

for locale in "${locales[@]}"; do
    lang="${locale:0:2}"

    loc_file="$(file_name ${locale})"
    lang_file="$(file_name ${lang})"

    echo "--- diffing ${loc_file} vs. ${lang_file} ---"

    diff "${loc_file}" "${lang_file}"

    echo -e "\n"
done
