#!/bin/bash

# guidgen - GUID generation
# generates the given number (or 0) of guids in lowercase, non-hyphenated format
#
# usage: guidgen [num]
#   - num: number of guids to generate. defaults to 1

if [ $# -eq 0 ]; then
    uuidgen | sed 's/-//g'
elif [ "$1" -eq "$1" ] 2>/dev/null; then
   for i in `seq 1 "$1"`; do
      echo "$i: " `uuidgen | sed 's/-//g'`
   done 
else
    echo "Usage: $0 [number]"
    exit 1
fi

exit 0
